[package]
name = "pd-sys"
version = "0.1.0"
authors = ["hnd <honda@softdevice.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
bindgen = "0.51.1"
